"""empty message

Revision ID: 002a1b861676
Revises: bff1e8abd2bc
Create Date: 2023-05-10 07:34:31.309681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002a1b861676'
down_revision = 'bff1e8abd2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('cart')

    # ### end Alembic commands ###
